### PR TITLE
wip-asdpc-superblock-voting: draft submission

### PR DESCRIPTION
**Pull request by aesedepece**
I'm submitting this draft to solve #45, as a followup to https://github.com/witnet/WIPs/blob/master/wip-0010.md

### CODE REVIEW

**Comment by aesedepece** [comment]
@lrubiorod if the submission looks correct to you, please assign a WIP number to it. Thanks!

**Comment by lrubiorod** [comment]
I assign you the WIP-0011

**Comment by aesedepece** [comment]
Thanks @lrubiorod! I have updated the WIP number on the document and the README accordingly. r?

**Comment by aesedepece** [comment]
The draft has been updated with the probability simulations made by @tmpolaczyk here:
https://github.com/tmpolaczyk/binomial_consensus/blob/master/binomial_consensus.ipynb

**Pull request merged**
